datawarehouse/api/kcidb/urls.py
"""Urls file."""
from django.urls import path

from . import views

urlpatterns = [
    path('data/<str:kind>', views.KCIDBView.as_view(),),
    path('submit', views.Submit.as_view()),

    path('revisions',
         views.RevisionList.as_view(), name='kcidb.revisions.list'),
    path('revisions/<str:id>',
         views.RevisionGet.as_view(), name='kcidb.revisions.get'),
    path('revisions/<str:id>/builds',
         views.BuildList.as_view(), name='kcidb.builds.list'),
    path('revisions/<str:id>/issues',
         views.RevisionIssueOccurrence.as_view(), name='kcidb.revisions.issues'),
    path('revisions/<str:id>/issues/<int:issue_id>',
         views.RevisionIssueOccurrence.as_view(), name='kcidb.revisions.issues'),
    path('builds/<str:id>',
         views.BuildGet.as_view(), name='kcidb.builds.get'),
    path('builds/<str:id>/tests',
         views.TestList.as_view(), name='kcidb.tests.list'),
    path('builds/<str:id>/issues',
         views.BuildIssueOccurrence.as_view(), name='kcidb.builds.issues'),
    path('builds/<str:id>/issues/<int:issue_id>',
         views.BuildIssueOccurrence.as_view(), name='kcidb.builds.issues'),
    path('tests/<str:id>',
         views.TestGet.as_view(), name='kcidb.tests.get'),
    path('tests/<str:id>/issues',
         views.TestIssueOccurrence.as_view(), name='kcidb.tests.issues'),
    path('tests/<str:id>/issues/<int:issue_id>',
         views.TestIssueOccurrence.as_view(), name='kcidb.tests.issues'),
]

datawarehouse/api/urls.py
"""Urls file."""
from django.urls import path, include
from . import views

urlpatterns = [
    path('1/pipeline/<int:pipeline_id>/action', views.PipelineAction.as_view()),
    path('1/pipeline/<int:pipeline_id>/issue/record', views.PipelineIssueRecord.as_view()),
    path('1/pipeline/<int:pipeline_id>/issue/record/<int:record_id>', views.PipelineIssueRecord.as_view()),
    path('1/pipeline/<int:pipeline_id>/report', views.PipelineReport.as_view()),
    path('1/pipeline/<int:pipeline_id>', views.Pipeline.as_view()),
    path('1/pipeline/<int:pipeline_id>/patches', views.PipelinePatches.as_view()),
    path('1/pipeline/<int:pipeline_id>/jobs/<str:stage_name>', views.PipelineJobs.as_view()),
    path('1/pipeline/<int:pipeline_id>/jobs/<str:stage_name>/failures', views.PipelineFailedJobs.as_view()),
    path('1/pipeline/failures/<str:stage_name>', views.PipelineByFailures.as_view()),
    path('1/issue/<int:issue_id>/record', views.IssueRecords.as_view()),
    path('1/issue/<int:issue_id>', views.Issue.as_view()),
    path('1/issue', views.Issue.as_view()),
    path('1/issue/regex', views.IssueRegex.as_view()),
    path('1/report/missing', views.ReportMissing.as_view()),
    path('1/test/<int:test_id>/issue/record', views.TestIssueRecord.as_view()),
    path('1/test/<int:test_id>/stats', views.TestStats.as_view()),
    path('1/test/<int:test_id>', views.TestSigle.as_view()),
    path('1/test', views.TestList.as_view()),
    path('1/kcidb/', include('datawarehouse.api.kcidb.urls')),
]

datawarehouse/urls.py
# -*- coding: utf-8 -*-
# Copyright (c) 2018 Red Hat, Inc. All rights reserved. This copyrighted
# material is made available to anyone wishing to use, modify, copy, or
# redistribute it subject to the terms and conditions of the GNU General Public
# License v.2 or later.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
"""Urls file."""
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

import debug_toolbar

from datawarehouse import views, views_kcidb
from datawarehouse.api.kcidb.views import KCIDBView

urlpatterns = [
    path('', RedirectView.as_view(url='dashboard', permanent=False)),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('confidence/<str:group>', views.confidence,),
    path('cron', views.cron_run,),
    path('dashboard', views.dashboard, name='Dashboard'),
    path('details/<str:group>/<int:item_id>', views.details,),
    path('issue/list/<str:group>', views.issue_list, name='issue_list'),
    path('issue/list', RedirectView.as_view(url='list/unresolved', permanent=False)),
    path('issue/regex', views.issue_regex, name='issue_regex'),
    path('issue', views.issue_new_or_edit,),
    path('issue/<int:issue_id>/resolve', views.issue_resolve,),
    path('issuerecord/<int:issue_record_id>/modify', views.issuerecord_modify),
    path('patches/submitter/<str:group>', views.patch_get_by_submitter),
    path('patches/summary/<str:group>', views.patch_summary),
    path('patches/submitter', RedirectView.as_view(url='submitter/tested', permanent=False, query_string=True)),
    path('patches', RedirectView.as_view(url='patches/summary/tested', permanent=False)),
    path('pipeline/summary', RedirectView.as_view(url='summary/all', permanent=False)),
    path('pipeline/summary/<str:tree>', views.pipeline_summary),
    path('pipeline/failures/<str:group>', views.pipelines_by_failure),
    path('pipeline/failures', RedirectView.as_view(url='failures/all', permanent=False)),
    path('pipeline/<int:pipeline_id>', views.pipeline_get, name='pipeline_get'),
    path('pipeline/<int:pipeline_id>/issue', views.pipeline_issue),
    path('pipeline/<int:pipeline_id>/issue/<int:issue_record_id>/delete', views.pipeline_issue_delete),
    path('pipeline/submitter', views.pipelines_get_by_submitter),
    path('pipeline/running', views.pipelines_running,),
    path('metrics', RedirectView.as_view(url='metrics/all', permanent=False)),
    path('metrics/<str:tree>', views.metrics,),

    path('kcidb/issues/occurrences', views_kcidb.kcidb_issue, name='views.kcidb.issues'),
    path('kcidb/revisions',
         views_kcidb.revisions_list, name='views.kcidb.revisions'),
    path('kcidb/revisions/<int:revision_iid>',
         views_kcidb.revisions_get, name='views.kcidb.revisions'),
    path('kcidb/builds/<int:build_iid>',
         views_kcidb.builds_get, name='views.kcidb.builds'),
    path('kcidb/tests/<int:test_iid>',
         views_kcidb.tests_get, name='views.kcidb.tests'),


    # The following url is only for compatibility.
    # It should be removed as soon as de kcidb scripts use the new endpoint.
    path('kcidb/1/data/<str:kind>', KCIDBView.as_view(),),
    path('api/', include('datawarehouse.api.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
] \
    + static(settings.MEDIA_PATH, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

datawarehouse/models/action_models.py
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2018-2019 Red Hat, Inc.

# pylint: disable=too-few-public-methods

"""Models related to actions."""

from django.db import models


class ActionKind(models.Model):
    """Model for ActionKind."""

    name = models.CharField(max_length=50)

    def __str__(self):
        """Return __str__ formatted."""
        return self.name


class Action(models.Model):
    """Model for PipelineAction."""

    created_at = models.DateTimeField(auto_now_add=True)
    kind = models.ForeignKey(ActionKind, on_delete=models.CASCADE)
    pipeline = models.ForeignKey('Pipeline',
                                 related_name='actions',
                                 on_delete=models.CASCADE)

    def __str__(self):
        """Return __str__ formatted."""
        return f'[{self.created_at}] {self.kind.name}'

datawarehouse/models/file_models.py
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2018-2019 Red Hat, Inc.

# pylint: disable=too-few-public-methods

"""Models related to the files."""
import pathlib
from urllib.parse import urlparse

from django.db import models


class Artifact(models.Model):
    """Model for Artifact."""

    name = models.CharField(max_length=150)
    url = models.URLField(max_length=400)

    def __str__(self):
        """Return __str__ formatted."""
        return f'{self.name}'

    def save(self, *args, **kwargs):
        # pylint: disable=arguments-differ
        """
        Override save method.

        Generate name from url if not provided.
        """
        if not self.name:
            path = urlparse(self.url).path
            self.name = pathlib.Path(path).name

        super(Artifact, self).save(*args, **kwargs)

    @classmethod
    def create_from_url(cls, url):
        """Create Artifact from url."""
        return cls.objects.get_or_create(url=url)[0]

datawarehouse/models/issue_models.py
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2018-2019 Red Hat, Inc.
"""Issue models file."""

from django.db import models
from django.db.models import Q

from datawarehouse import models as dw_models


class IssueKind(models.Model):
    """Model for IssueKind."""

    description = models.CharField(max_length=200)
    tag = models.CharField(max_length=20)
    color = models.CharField(max_length=7, default='#dc3545')
    kernel_code_related = models.BooleanField(default=False)

    def __str__(self):
        """Return __str__ formatted."""
        return f'{self.description}'


class Issue(models.Model):
    """Model for Issue."""

    kind = models.ForeignKey(IssueKind, on_delete=models.CASCADE, null=True)
    description = models.CharField(max_length=200)
    ticket_url = models.URLField(unique=True)
    resolved = models.BooleanField(default=False)
    generic = models.BooleanField(default=False)
    origin_tree = models.ForeignKey('GitTree', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        """Return __str__ formatted."""
        return f'{self.description}'

    @property
    def pipelines(self):
        """Return all pipelines linked through records."""
        return (
            dw_models.Pipeline.objects
            .filter(
                id__in=self.issue_records.values_list('pipeline__id', flat=True)
            )
            .select_related(
                'gittree',
            )
            .prefetch_related(
                'issue_records',
                'reports',
                'variables',
                'lint_jobs',
                'merge_jobs',
                'build_jobs',
                'test_jobs',
                'test_jobs__result',
            )
            .add_stats()
        )

    class Meta:
        """Meta."""

        ordering = ('-id', )

    @property
    def revisions(self):
        """Return all revisions linked through occurrences."""
        return dw_models.KCIDBRevision.objects.filter(
            Q(id__in=self.kcidbrevision_set.values_list('id', flat=True)) |
            Q(kcidbbuild__in=self.kcidbbuild_set.all()) |
            Q(kcidbbuild__kcidbtest__in=self.kcidbtest_set.all())
        ).distinct().order_by('-iid')


class IssueRecord(models.Model):
    """Model for IssueRecord."""

    issue = models.ForeignKey(Issue, on_delete=models.CASCADE, related_name='issue_records')
    pipeline = models.ForeignKey('Pipeline',
                                 related_name='issue_records',
                                 on_delete=models.CASCADE)
    testruns = models.ManyToManyField('TestRun', related_name='issue_records')
    bot_generated = models.BooleanField(default=False)

    def __str__(self):
        """Return __str__ formatted."""
        return f'{self.pipeline.pipeline_id} - {self.issue.description}'

    class Meta:
        """Metadata."""

        ordering = ('-id',)


class IssueRegex(models.Model):
    """Model for IssueRegex."""

    issue = models.ForeignKey(Issue, on_delete=models.CASCADE, related_name='issue_regexes')
    text_match = models.CharField(max_length=200)
    file_name_match = models.CharField(max_length=200, null=True, default=None)
    test_name_match = models.CharField(max_length=200, null=True, default=None)

    def __str__(self):
        """Return __str__ formatted."""
        return f'{self.test_name_match} - {self.file_name_match} - {self.text_match}'

datawarehouse/models/lookups.py
"""Lookup helpers."""
from django.db.models import Lookup
from django.db.models.fields import Field


@Field.register_lookup
class NotEqualLookup(Lookup):
    """Implement the SQL <> operator."""

    lookup_name = 'ne'

    def as_sql(self, compiler, connection):
        """Generate the sql query."""
        lhs, lhs_params = self.process_lhs(compiler, connection)
        rhs, rhs_params = self.process_rhs(compiler, connection)
        params = lhs_params + rhs_params
        return '%s <> %s' % (lhs, rhs), params


@Field.register_lookup
class NotInLookup(Lookup):
    """Implement the SQL NOT IN operator.

    Adapted from django.db.models.lookups. Most probably only works for simple
    lists.
    """

    lookup_name = 'not_in'

    def process_rhs(self, compiler, connection):
        """Process in a loop."""
        sqls, sqls_params = self.batch_process_rhs(compiler, connection, self.rhs)
        placeholder = '(' + ', '.join(sqls) + ')'
        return (placeholder, sqls_params)

    def get_db_prep_lookup(self, value, connection):
        """Prepare in a loop."""
        return ('%s', [self.lhs.output_field.get_db_prep_value(v, connection, prepared=True) for v in value])

    def get_prep_lookup(self):
        """Prepare in a loop."""
        return [self.lhs.output_field.get_prep_value(v) for v in self.rhs]

    def as_sql(self, compiler, connection):
        """Generate the sql query."""
        self.rhs = set(self.rhs)
        lhs, lhs_params = self.process_lhs(compiler, connection)
        rhs, rhs_params = self.process_rhs(compiler, connection)
        params = lhs_params + rhs_params
        return '%s NOT IN %s' % (lhs, rhs), params

datawarehouse/models/message_models.py
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2018-2019 Red Hat, Inc.

# pylint: disable=too-few-public-methods

"""Models related to messages."""

from django.db import models


class MessagePending(models.Model):
    """Model for MessagePending."""

    body = models.TextField()
    exchange = models.CharField(max_length=50)

    def __str__(self):
        """Return __str__ formatted."""
        return self.body

datawarehouse/models/report_models.py
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2018-2019 Red Hat, Inc.
"""Report models file."""

from django.db import models


class Recipient(models.Model):
    """Model for Recipient."""

    email = models.EmailField()

    def __str__(self):
        """Return __str__ formatted."""
        return f'{self.email}'


class Report(models.Model):
    """Model for Report."""

    pipeline = models.ForeignKey('Pipeline',
                                 related_name='reports',
                                 on_delete=models.CASCADE)

    subject = models.CharField(max_length=200)
    msgid = models.CharField(max_length=200, unique=True)
    body = models.TextField()
    addr_to = models.ManyToManyField(Recipient, related_name='addr_to')
    addr_cc = models.ManyToManyField(Recipient, related_name='addr_cc')
    sent_at = models.DateTimeField()
    raw = models.TextField()

    def __str__(self):
        """Return __str__ formatted."""
        return f'{self.pipeline.pipeline_id} - {self.msgid}'

datawarehouse/templates/web/confidence.html
{% extends "base.html" %}

{% block title %}
{{ group|title }} Confidence
{% endblock %}

{% block header %}

{{ group|title }} Stats

{% load addstr %}
{% include "search.html" with name="search" action="/confidence/"|addstr:group placeholder="Filter" clearhref="/confidence/"|addstr:group|addstr:"?days_ago="|addstr:since hidden_name="days_ago" hidden_value=since %}
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-xl-4 col-md-6 mb-4">
    <i class="fas fa-history"></i>
      Since {{since}} days ago
      (
      {% with value="ever" name="Since ever" %}
      {% include 'confidence_time_filter.html' %}
      {% endwith %}

      {% with value="7" name="7 days" %}
      {% include 'confidence_time_filter.html' %}
      {% endwith %}

      {% with value="1" name="1 day" %}
      {% include 'confidence_time_filter.html' %}
      {% endwith %}
      )
  </div>
</div>

<div class="row">

{% for item in map %}
  <div class="col-md-4">
  {% include 'web/confidence_column.html' %}
  </div>
{% endfor %}

</div>
{% endblock %}

datawarehouse/templates/web/confidence_column.html
<div class="card shadow mb-4">
  <div class="card-header py-3">
      {% if group == 'tests' %}
      <h6 class="m-0 font-weight-bold text-primary"><a href="/details/test/{{item.item.id}}">{{item.item.name}}</a></h6>
      {% else %}
      <h6 class="m-0 font-weight-bold text-primary"><a href="/details/host/{{item.item.id}}">{{item.item.fqdn}}</a></h6>
      {% endif %}
  </div>
  <div class="card-body">
      <h4 class="small font-weight-bold">Results <span class="float-right">Confidence: {{item.confidence|floatformat:3}} | {{item.total}} jobs</span></h4>

    <div class="progress mb-4">
      <div title="{{item.results.PASS}} job(s)" class="progress-bar bg-success" style="width:{{item.results_percent.PASS}}%">
          Pass
      </div>
      <div title="{{item.results.SKIP}} job(s)" class="progress-bar bg-gray-800" style="width:{{item.results_percent.SKIP}}%">
          Skip
      </div>
      <div title="{{item.results.FAIL}} job(s)" class="progress-bar bg-danger" style="width:{{item.results_percent.FAIL}}%">
          Fail
      </div>
      <div title="{{item.results.ERROR}} job(s)" class="progress-bar bg-danger" style="width:{{item.results_percent.ERROR}}%">
          Error
      </div>
    </div>
  </div>
</div>

datawarehouse/templates/web/failures.html
{% extends "base.html" %}

{% block title %}
Failed Pipelines
{% endblock %}

{% block header %}
Failed Pipelines
{% endblock %}

{% block content %}

<ul class="nav nav-tabs mb-3">
  <li class="nav-item"><a class="nav-link {% if group == "all" %}active{% endif %}" href="all">All</a></li>
  {% for stage in stages %}
    <li class="nav-item"><a class="nav-link {% if group == stage.name %}active{% endif %}" href="{{ stage.name }}">{{ stage.name|title }}</a></li>
  {% endfor %}
</ul>

<div class="tab-content">
  <div class="tab-pane active">
    <div class="card shadow mb-4">
      <div class="card-body">
        {% include 'tables/table_pipelines_failures.html' %}
      </div>
    </div>
    {% include 'paginator.html' with paginator=pipelines %}
  </div>
</div>

{% endblock %}

datawarehouse/templates/web/issue_regex.html
{% extends "base.html" %}
{% load serialize %}

{% block title %}
Issues Regexes
{% endblock %}

{% block header %}
Issues Regexes
{% endblock %}

{% block content %}

{% if perms.datawarehouse.add_issueregex %}
{% include 'modal_new_issue_regex.html' %}
{% endif %}

<div class="tab-content">
  <div class="tab-pane active">

    {% if perms.datawarehouse.add_issueregex %}
    <div class="col-xl-4 col-md-6 mb-4">
      <div class="row">
        <span class="dropdown">
          <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Actions
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="#" onclick="openIssueRegexModal('new', '')">New Issue Regex</a>
          </div>
        </span>
      </div>
    </div>
    {% endif %}

    {% for issue_regex in issue_regexes %}
    {% include 'card_issue_regex.html' %}
    {% endfor %}

  </div>
</div>

{% with paginator=issue_regex %}
{% include 'paginator.html' %}
{% endwith %}

{% endblock %}

{% block script %}
<script type="text/javascript">
  var url = window.location.href;
  if (url.indexOf('#issueregex') != -1) {
      $('#issueRegexModal').modal('show');
  }
</script>

<script>
   function openIssueRegexModal(action, regex) {
     var x = document.getElementById("delete_issue_regex");
     if (action === 'new') {
       x.style.display = "none";
     } else {
       document.getElementById("issue_regex_id").value = regex['id'];
       document.getElementById("issue_id_select").value = regex['issue']['id'];
       document.getElementById("issue_regex_text_match").value = regex['text_match'];
       document.getElementById("issue_regex_test_name_match").value = regex['test_name_match'];
       document.getElementById("issue_regex_file_name_match").value = regex['file_name_match'];
       document.getElementById("action").value = "edit";
       x.style.display = "block";
     }
     $('#issueRegexModal').modal('show');
   };
</script>
{% endblock %}

datawarehouse/templates/web/issues_list.html
{% extends "base.html" %}

{% block title %}
Issues
{% endblock %}

{% block header %}
Issues List
{% load addstr %}
{% include 'search.html' with name="search" action="/issue/list/"|addstr:group placeholder="Search for issues..." clearhref="/issue/list/"|addstr:group %}

{% if perms.datawarehouse.add_issue %}
<button class="btn btn-primary ml-2" type="button" onclick="newIssueButton()">
  New Issue
</button>
{% endif %}

{% endblock %}

{% block content %}

<ul class="nav nav-tabs mb-3">
    <li class="nav-item"><a class="nav-link {% if group == "unresolved" %}active{% endif %}" href="unresolved?search={{ search }}">Unresolved</a></li>
    <li class="nav-item"><a class="nav-link {% if group == "resolved" %}active{% endif %}" href="resolved?search={{ search }}">Resolved</a></li>
</ul>

{% if perms.datawarehouse.add_issue or perms.datawarehouse.change_issue %}
<div class="col-xl-12 col-md-12 mb-2">
  <div class="collapse {% if request.GET.new %}show{% endif %}" id="collapseIssueForm">
    <div class="card card-body">
        <form action="/issue" method="post">
          {% csrf_token %}
          <div class="modal-body">
            <div class="form-group">
              <label for="issue_id">ID</label>
              <input type="text" class="form-control" name="issue_id" placeholder="Autogenerated" id="issue_id" readonly>
            </div>
            <div class="form-group">
              <label for="issue_description">Description</label>
              <input required="required" type="text" class="form-control" name="description" placeholder="Enter description" id="issue_description">
            </div>
            <div class="form-group">
              <label for="issue_url">Ticket URL</label>
              <input required="required" type="url" class="form-control" name="ticket_url" placeholder="Enter ticket URL (Jira, Bugzilla, etc)" id="issue_url">
            </div>
            <div class="form-group">
              <label for="issue_kind_id">Issue Kind</label>
              <select required="required" class="form-control" id="issue_kind_id" name="kind_id">
              <option disabled selected>Select an option</option>
                {% for kind in issue_kinds %}
                <option value="{{ kind.id }}" data-kernel-related="{{ kind.kernel_code_related }}">{{ kind.description }}</option>
                {% endfor %}
              </select>
            </div>
            <div class="form-group" id="issue_origin_tree_container" style="display: none">
              <label for="issue_origin_tree_id">Issue Origin (where it first appeared)</label>
              <select required="required" class="form-control" id="issue_origin_tree_id" name="origin_tree_id">
              <option value="0" selected>&lt;Unknown&gt;</option>
                {% for tree in git_trees %}
                <option value="{{ tree.id }}">{{ tree.name }}</option>
                {% endfor %}
              </select>
            </div>
            <div class="form-check">
              <input type="checkbox" class="form-check-input" id="issue_generic" name="generic">
              <label class="form-check-label" for="issue_generic">Generic</label>
            </div>
            <div class="form-check">
              <input type="checkbox" class="form-check-input" id="issue_resolved" name="resolved">
              <label class="form-check-label" for="issue_resolved">Resolved</label>
            </div>
          </div>
          <input type="hidden" name="redirect_to" value="{% firstof request.GET.redirect_to request.get_full_path %}"/>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-toggle="collapse" data-target="#collapseIssueForm">Cancel</button>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
        </form>
    </div>
  </div>
</div>
{% endif %}

<div class="tab-content">
  <div class="tab-pane active">
    {% for issue in issues %}
      {% include "card_issues_list.html" %}
    {% endfor %}
    {% include 'paginator.html' with paginator=issues extra_arguments="&search="|addstr:search %}
  </div>
</div>

{% endblock %}

{% block script %}
<script>
  function newIssueButton() {
    document.getElementById("issue_id").value = '';
    document.getElementById("issue_description").value = '';
    document.getElementById("issue_url").value = '';
    document.getElementById("issue_kind_id").value = '';
    afterUpdateIssueKind(document.getElementById("issue_kind_id"));
    document.getElementById("issue_origin_tree_id").options[0].selected = true;
    document.getElementById("issue_resolved").checked = false;
    document.getElementById("issue_generic").checked = false;
    $('#collapseIssueForm').collapse('show');
  };

  function editIssue(issue) {
    document.getElementById("issue_id").value = issue['id'];
    document.getElementById("issue_description").value = issue['description'];
    document.getElementById("issue_url").value = issue['ticket_url'];
    document.getElementById("issue_kind_id").value = issue['kind']['id'];
    afterUpdateIssueKind(document.getElementById("issue_kind_id"));
    for (let option of document.getElementById("issue_origin_tree_id").options) {
      if (issue.origin_tree && option.value == issue.origin_tree.id) {
        option.selected = true;
      }
    }
    document.getElementById("issue_resolved").checked = issue['resolved'];
    document.getElementById("issue_generic").checked = issue['generic'];
    $('#collapseIssueForm').collapse('show');
  }

  function afterUpdateIssueKind(issueKindDropdown) {
    const selectedOption = issueKindDropdown.selectedOptions[0];
    const isIssueKernelCodeRelated = selectedOption && selectedOption.dataset.kernelRelated.toLowerCase() === 'true';

    $('#issue_origin_tree_container').toggle(isIssueKernelCodeRelated);
  }

  $('#issue_kind_id').change(function(evt) {
      afterUpdateIssueKind(evt.currentTarget);
  });
</script>
{% endblock %}

datawarehouse/templates/web/metrics.html
{% extends "base.html" %}

{% block title %}
Metrics Dashboard
{% endblock %}

{% block header %}
Metrics for {{ tree }}
{% endblock %}

{% block content %}

<div class="col-xl-12 mb-2">
  {% for filter in days_filter_available %}
  <a href="?from={{ filter }}" class="d-none d-sm-inline-block btn btn-sm shadow-sm
    {% if filter == days_filter %} btn-primary {% else %} btn-secondary {% endif %}">
    {{ filter|title }}</a>
  {% endfor %}
</div>

<ul class="nav nav-tabs mb-3">
      <a class="nav-link {% if tree == 'all' %}active{% endif %}" href="all?from={{ days_filter }}">All</a>
    {% for available_tree in trees %}
    <li class="nav-item">
      <a class="nav-link {% if tree == available_tree.name %}active{% endif %}" href="{{ available_tree.name }}?from={{ days_filter }}">
        {{available_tree.name}}
      </a>
    </li>
    {% endfor %}
</ul>

{% for group in groups %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{ group.title }}</h1>
</div>
<div class="row">
{% for plot in group.plots %}
    {% if plot.type == 'doughnut' %}
      {% include 'plots/doughnut.html' %}
    {% elif plot.type == 'area' %}
      {% include 'plots/area.html' %}
    {% endif %}
{% endfor %}
</div>
{% endfor %}

{% endblock %}


{% block script %}

{% endblock %}