datawarehouse/api/kcidb/urls.py
"""Urls file."""
from django.urls import path

from . import views

urlpatterns = [
    path('data/<str:kind>', views.KCIDBView.as_view(),),
    path('submit', views.Submit.as_view()),

    path('revisions',
         views.RevisionList.as_view(), name='kcidb.revisions.list'),
    path('revisions/<str:id>',
         views.RevisionGet.as_view(), name='kcidb.revisions.get'),
    path('revisions/<str:id>/builds',
         views.BuildList.as_view(), name='kcidb.builds.list'),
    path('revisions/<str:id>/issues',
         views.RevisionIssueOccurrence.as_view(), name='kcidb.revisions.issues'),
    path('revisions/<str:id>/issues/<int:issue_id>',
         views.RevisionIssueOccurrence.as_view(), name='kcidb.revisions.issues'),
    path('builds/<str:id>',
         views.BuildGet.as_view(), name='kcidb.builds.get'),
    path('builds/<str:id>/tests',
         views.TestList.as_view(), name='kcidb.tests.list'),
    path('builds/<str:id>/issues',
         views.BuildIssueOccurrence.as_view(), name='kcidb.builds.issues'),
    path('builds/<str:id>/issues/<int:issue_id>',
         views.BuildIssueOccurrence.as_view(), name='kcidb.builds.issues'),
    path('tests/<str:id>',
         views.TestGet.as_view(), name='kcidb.tests.get'),
    path('tests/<str:id>/issues',
         views.TestIssueOccurrence.as_view(), name='kcidb.tests.issues'),
    path('tests/<str:id>/issues/<int:issue_id>',
         views.TestIssueOccurrence.as_view(), name='kcidb.tests.issues'),
]

datawarehouse/api/urls.py
"""Urls file."""
from django.urls import path, include
from . import views

urlpatterns = [
    path('1/pipeline/<int:pipeline_id>/action', views.PipelineAction.as_view()),
    path('1/pipeline/<int:pipeline_id>/issue/record', views.PipelineIssueRecord.as_view()),
    path('1/pipeline/<int:pipeline_id>/issue/record/<int:record_id>', views.PipelineIssueRecord.as_view()),
    path('1/pipeline/<int:pipeline_id>/report', views.PipelineReport.as_view()),
    path('1/pipeline/<int:pipeline_id>', views.Pipeline.as_view()),
    path('1/pipeline/<int:pipeline_id>/patches', views.PipelinePatches.as_view()),
    path('1/pipeline/<int:pipeline_id>/jobs/<str:stage_name>', views.PipelineJobs.as_view()),
    path('1/pipeline/<int:pipeline_id>/jobs/<str:stage_name>/failures', views.PipelineFailedJobs.as_view()),
    path('1/pipeline/failures/<str:stage_name>', views.PipelineByFailures.as_view()),
    path('1/issue/<int:issue_id>/record', views.IssueRecords.as_view()),
    path('1/issue/<int:issue_id>', views.Issue.as_view()),
    path('1/issue', views.Issue.as_view()),
    path('1/issue/regex', views.IssueRegex.as_view()),
    path('1/report/missing', views.ReportMissing.as_view()),
    path('1/test/<int:test_id>/issue/record', views.TestIssueRecord.as_view()),
    path('1/test/<int:test_id>/stats', views.TestStats.as_view()),
    path('1/test/<int:test_id>', views.TestSigle.as_view()),
    path('1/test', views.TestList.as_view()),
    path('1/kcidb/', include('datawarehouse.api.kcidb.urls')),
]

datawarehouse/urls.py
# -*- coding: utf-8 -*-
# Copyright (c) 2018 Red Hat, Inc. All rights reserved. This copyrighted
# material is made available to anyone wishing to use, modify, copy, or
# redistribute it subject to the terms and conditions of the GNU General Public
# License v.2 or later.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
"""Urls file."""
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

import debug_toolbar

from datawarehouse import views, views_kcidb
from datawarehouse.api.kcidb.views import KCIDBView

urlpatterns = [
    path('', RedirectView.as_view(url='dashboard', permanent=False)),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('confidence/<str:group>', views.confidence,),
    path('cron', views.cron_run,),
    path('dashboard', views.dashboard, name='Dashboard'),
    path('details/<str:group>/<int:item_id>', views.details,),
    path('issue/list/<str:group>', views.issue_list, name='issue_list'),
    path('issue/list', RedirectView.as_view(url='list/unresolved', permanent=False)),
    path('issue/regex', views.issue_regex, name='issue_regex'),
    path('issue', views.issue_new_or_edit,),
    path('issue/<int:issue_id>/resolve', views.issue_resolve,),
    path('issuerecord/<int:issue_record_id>/modify', views.issuerecord_modify),
    path('patches/submitter/<str:group>', views.patch_get_by_submitter),
    path('patches/summary/<str:group>', views.patch_summary),
    path('patches/submitter', RedirectView.as_view(url='submitter/tested', permanent=False, query_string=True)),
    path('patches', RedirectView.as_view(url='patches/summary/tested', permanent=False)),
    path('pipeline/summary', RedirectView.as_view(url='summary/all', permanent=False)),
    path('pipeline/summary/<str:tree>', views.pipeline_summary),
    path('pipeline/failures/<str:group>', views.pipelines_by_failure),
    path('pipeline/failures', RedirectView.as_view(url='failures/all', permanent=False)),
    path('pipeline/<int:pipeline_id>', views.pipeline_get, name='pipeline_get'),
    path('pipeline/<int:pipeline_id>/issue', views.pipeline_issue),
    path('pipeline/<int:pipeline_id>/issue/<int:issue_record_id>/delete', views.pipeline_issue_delete),
    path('pipeline/submitter', views.pipelines_get_by_submitter),
    path('pipeline/running', views.pipelines_running,),
    path('metrics', RedirectView.as_view(url='metrics/all', permanent=False)),
    path('metrics/<str:tree>', views.metrics,),

    path('kcidb/issues/occurrences', views_kcidb.kcidb_issue, name='views.kcidb.issues'),
    path('kcidb/revisions',
         views_kcidb.revisions_list, name='views.kcidb.revisions'),
    path('kcidb/revisions/<int:revision_iid>',
         views_kcidb.revisions_get, name='views.kcidb.revisions'),
    path('kcidb/builds/<int:build_iid>',
         views_kcidb.builds_get, name='views.kcidb.builds'),
    path('kcidb/tests/<int:test_iid>',
         views_kcidb.tests_get, name='views.kcidb.tests'),


    # The following url is only for compatibility.
    # It should be removed as soon as de kcidb scripts use the new endpoint.
    path('kcidb/1/data/<str:kind>', KCIDBView.as_view(),),
    path('api/', include('datawarehouse.api.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
] \
    + static(settings.MEDIA_PATH, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

datawarehouse/models/action_models.py
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2018-2019 Red Hat, Inc.

# pylint: disable=too-few-public-methods

"""Models related to actions."""

from django.db import models


class ActionKind(models.Model):
    """Model for ActionKind."""

    name = models.CharField(max_length=50)

    def __str__(self):
        """Return __str__ formatted."""
        return self.name


class Action(models.Model):
    """Model for PipelineAction."""

    created_at = models.DateTimeField(auto_now_add=True)
    kind = models.ForeignKey(ActionKind, on_delete=models.CASCADE)
    pipeline = models.ForeignKey('Pipeline',
                                 related_name='actions',
                                 on_delete=models.CASCADE)

    def __str__(self):
        """Return __str__ formatted."""
        return f'[{self.created_at}] {self.kind.name}'

datawarehouse/models/file_models.py
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2018-2019 Red Hat, Inc.

# pylint: disable=too-few-public-methods

"""Models related to the files."""
import pathlib
from urllib.parse import urlparse

from django.db import models


class Artifact(models.Model):
    """Model for Artifact."""

    name = models.CharField(max_length=150)
    url = models.URLField(max_length=400)

    def __str__(self):
        """Return __str__ formatted."""
        return f'{self.name}'

    def save(self, *args, **kwargs):
        # pylint: disable=arguments-differ
        """
        Override save method.

        Generate name from url if not provided.
        """
        if not self.name:
            path = urlparse(self.url).path
            self.name = pathlib.Path(path).name

        super(Artifact, self).save(*args, **kwargs)

    @classmethod
    def create_from_url(cls, url):
        """Create Artifact from url."""
        return cls.objects.get_or_create(url=url)[0]

datawarehouse/models/issue_models.py
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2018-2019 Red Hat, Inc.
"""Issue models file."""

from django.db import models
from django.db.models import Q

from datawarehouse import models as dw_models


class IssueKind(models.Model):
    """Model for IssueKind."""

    description = models.CharField(max_length=200)
    tag = models.CharField(max_length=20)
    color = models.CharField(max_length=7, default='#dc3545')
    kernel_code_related = models.BooleanField(default=False)

    def __str__(self):
        """Return __str__ formatted."""
        return f'{self.description}'


class Issue(models.Model):
    """Model for Issue."""

    kind = models.ForeignKey(IssueKind, on_delete=models.CASCADE, null=True)
    description = models.CharField(max_length=200)
    ticket_url = models.URLField(unique=True)
    resolved = models.BooleanField(default=False)
    generic = models.BooleanField(default=False)
    origin_tree = models.ForeignKey('GitTree', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        """Return __str__ formatted."""
        return f'{self.description}'

    @property
    def pipelines(self):
        """Return all pipelines linked through records."""
        return (
            dw_models.Pipeline.objects
            .filter(
                id__in=self.issue_records.values_list('pipeline__id', flat=True)
            )
            .select_related(
                'gittree',
            )
            .prefetch_related(
                'issue_records',
                'reports',
                'variables',
                'lint_jobs',
                'merge_jobs',
                'build_jobs',
                'test_jobs',
                'test_jobs__result',
            )
            .add_stats()
        )

    class Meta:
        """Meta."""

        ordering = ('-id', )

    @property
    def revisions(self):
        """Return all revisions linked through occurrences."""
        return dw_models.KCIDBRevision.objects.filter(
            Q(id__in=self.kcidbrevision_set.values_list('id', flat=True)) |
            Q(kcidbbuild__in=self.kcidbbuild_set.all()) |
            Q(kcidbbuild__kcidbtest__in=self.kcidbtest_set.all())
        ).distinct().order_by('-iid')


class IssueRecord(models.Model):
    """Model for IssueRecord."""

    issue = models.ForeignKey(Issue, on_delete=models.CASCADE, related_name='issue_records')
    pipeline = models.ForeignKey('Pipeline',
                                 related_name='issue_records',
                                 on_delete=models.CASCADE)
    testruns = models.ManyToManyField('TestRun', related_name='issue_records')
    bot_generated = models.BooleanField(default=False)

    def __str__(self):
        """Return __str__ formatted."""
        return f'{self.pipeline.pipeline_id} - {self.issue.description}'

    class Meta:
        """Metadata."""

        ordering = ('-id',)


class IssueRegex(models.Model):
    """Model for IssueRegex."""

    issue = models.ForeignKey(Issue, on_delete=models.CASCADE, related_name='issue_regexes')
    text_match = models.CharField(max_length=200)
    file_name_match = models.CharField(max_length=200, null=True, default=None)
    test_name_match = models.CharField(max_length=200, null=True, default=None)

    def __str__(self):
        """Return __str__ formatted."""
        return f'{self.test_name_match} - {self.file_name_match} - {self.text_match}'

datawarehouse/models/lookups.py
"""Lookup helpers."""
from django.db.models import Lookup
from django.db.models.fields import Field


@Field.register_lookup
class NotEqualLookup(Lookup):
    """Implement the SQL <> operator."""

    lookup_name = 'ne'

    def as_sql(self, compiler, connection):
        """Generate the sql query."""
        lhs, lhs_params = self.process_lhs(compiler, connection)
        rhs, rhs_params = self.process_rhs(compiler, connection)
        params = lhs_params + rhs_params
        return '%s <> %s' % (lhs, rhs), params


@Field.register_lookup
class NotInLookup(Lookup):
    """Implement the SQL NOT IN operator.

    Adapted from django.db.models.lookups. Most probably only works for simple
    lists.
    """

    lookup_name = 'not_in'

    def process_rhs(self, compiler, connection):
        """Process in a loop."""
        sqls, sqls_params = self.batch_process_rhs(compiler, connection, self.rhs)
        placeholder = '(' + ', '.join(sqls) + ')'
        return (placeholder, sqls_params)

    def get_db_prep_lookup(self, value, connection):
        """Prepare in a loop."""
        return ('%s', [self.lhs.output_field.get_db_prep_value(v, connection, prepared=True) for v in value])

    def get_prep_lookup(self):
        """Prepare in a loop."""
        return [self.lhs.output_field.get_prep_value(v) for v in self.rhs]

    def as_sql(self, compiler, connection):
        """Generate the sql query."""
        self.rhs = set(self.rhs)
        lhs, lhs_params = self.process_lhs(compiler, connection)
        rhs, rhs_params = self.process_rhs(compiler, connection)
        params = lhs_params + rhs_params
        return '%s NOT IN %s' % (lhs, rhs), params

datawarehouse/models/message_models.py
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2018-2019 Red Hat, Inc.

# pylint: disable=too-few-public-methods

"""Models related to messages."""

from django.db import models


class MessagePending(models.Model):
    """Model for MessagePending."""

    body = models.TextField()
    exchange = models.CharField(max_length=50)

    def __str__(self):
        """Return __str__ formatted."""
        return self.body

datawarehouse/models/report_models.py
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2018-2019 Red Hat, Inc.
"""Report models file."""

from django.db import models


class Recipient(models.Model):
    """Model for Recipient."""

    email = models.EmailField()

    def __str__(self):
        """Return __str__ formatted."""
        return f'{self.email}'


class Report(models.Model):
    """Model for Report."""

    pipeline = models.ForeignKey('Pipeline',
                                 related_name='reports',
                                 on_delete=models.CASCADE)

    subject = models.CharField(max_length=200)
    msgid = models.CharField(max_length=200, unique=True)
    body = models.TextField()
    addr_to = models.ManyToManyField(Recipient, related_name='addr_to')
    addr_cc = models.ManyToManyField(Recipient, related_name='addr_cc')
    sent_at = models.DateTimeField()
    raw = models.TextField()

    def __str__(self):
        """Return __str__ formatted."""
        return f'{self.pipeline.pipeline_id} - {self.msgid}'

datawarehouse/templates/card_issue_record.html
{% include 'modal_edit_issue_record.html' with issue_record=record failed_test_jobs=failed_test_jobs %}

<div class="col-xl-12 col-md-12 mb-2">
    <div class="card border-bottom-danger shadow h-100 py-2">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
          <div class="text-xs font-weight-bold text-uppercase mb-1">
              Related Issue

              {% if record.bot_generated %}
              <span class="badge badge-primary" style="background-color: #3399FFA0" title="Beep beep. This issue was recorded by a script.">Bot Generated</span>
              {% endif %}

              <div class="action-icons-right">
                {% if perms.datawarehouse.change_issuerecord or perms.datawarehouse.delete_issuerecord %}
                <button type="button" href="#" data-toggle="modal" data-dismiss="modal" data-target="#editIssueRecordModal{{ record.id }}">
                  <span><i class="fas fa-sm fa-pen"></i></span>
                </button>
                {% endif %}
              </div>
          </div>
          <div class="h5 mb-1 font-weight-bold">
            {% include 'issue_kind_badge.html' %}
            <a href="{{record.issue.ticket_url}}">
                {{record.issue.description}}
            </a>
            {% if record.issue.kind.kernel_code_related %}
            <span class="badge badge-secondary" title="Origin tree: {{ record.issue.origin_tree.name|default:'unknown' }}">{{ record.issue.origin_tree.name|default:'unknown' }}</span>
            {% endif %}
          </div>
          {% with test_jobs=record.testruns.all %}
          {% include 'tables/table_testrun_issue_record.html' %}
          {% endwith %}
        </div>
      </div>
    </div>
  </div>
</div>

datawarehouse/templates/card_issue_regex.html
{% load serialize %}
<div class="card border-bottom-primary shadow h-100 mb-1">
  <div class="card-body">
    <div class="row no-gutters align-items-center">
      <div class="col mr-2">
        <div class="row">
          <div class="col-xl-12">
            <label>Issue:</label>
              <a href="{% url 'issue_list' 'unresolved' %}?search={{issue_regex.issue.description}}">{{issue_regex.issue.description}}</a>
              {% if perms.datawarehouse.change_issueregex or perms.datawarehouse.delete_issueadd %}
              <button type="button" class="close" href="#" onclick="openIssueRegexModal('edit', {{ issue_regex|serialize:'IssueRegexSerializer' }})">
                <span>
                  <i class="fas fa-xs fa-pen"></i>
                </span>
              </button>
              {% endif %}
          </div>
        </div>
        <div class="row">
          <div class="col-xl-4">
            <label>Text Match: </label> {{ issue_regex.text_match }}
          </div>
          <div class="col-xl-4">
            <label>File Name Match: </label> {{ issue_regex.file_name_match }}
          </div>
          <div class="col-xl-4">
            <label>Test Name Match: </label> {{ issue_regex.test_name_match }}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

datawarehouse/templates/modal_edit_issue_record.html
{% if perms.datawarehouse.change_issuerecord or perms.datawarehouse.delete_issuerecord %}
<!-- Delete Record Modal -->
<div class="modal fade" id="deleteRecord{{ record.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteRecord{{ record.id }}Label" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
          <h5 class="modal-title" id="deleteRecord{{ record.id }}Label">Confirm action.</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          Are you sure
          <i>{{ record.issue.description }}</i>
          doesn't belong in this pipeline?
          <br/>
          <br/>
          <b>This action cannot be undone.</b>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <form method="post" action="/pipeline/{{pipeline.pipeline_id}}/issue/{{record.id}}/delete">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">Confirm</button>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- End Delete Record Modal -->
{% endif %}

<!-- Edit Issue Record Modal -->
<div class="modal fade" id="editIssueRecordModal{{ issue_record.id }}" tabindex="-1" role="dialog" aria-labelledby="editIssueRecordModal{{ issue_record.id }}Label" aria-hidden="true">
  <div class="modal-dialog  modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
          <h5 class="modal-title" id="editIssueRecordModal{{ issue_record.id }}Label">Associate Issue to Pipeline #{{ pipeline.pipeline_id }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="/issuerecord/{{ issue_record.id }}/modify" method="post">
          {% csrf_token %}
          <div class="form-group">
            <label for="testTable">Faulty Test Runs (optional)</label>
            <div class="table-responsive">
              <table class="table table-bordered" id="testTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    {% if perms.datawarehouse.change_issuerecord %}
                    <th></th>
                    {% endif %}
                    <th>Result</th>
                    <th>Test</th>
                    <th>Arch</th>
                    <th>Beaker Task</th>
                    <th>Gitlab Job</th>
                  </tr>
                </thead>
                <tbody>
                  {% for testrun in failed_test_jobs %}
                    {% if perms.datawarehouse.change_issuerecord or testrun in issue_record.testruns.all %}
                  <tr class="{{ testrun.passed_style.cell }}">
                    {% if perms.datawarehouse.change_issuerecord %}
                      <td>
                        <input type="checkbox" value="{{testrun.id}}" name="testrun_ids"
                          {% if testrun in issue_record.testruns.all %}
                          checked="checked"
                          {% endif %}>
                      </td>
                      {% endif %}
                      <td align="center" class="{{ testrun.passed_style.cell }}" title="{{testrun.result.name}}">
                        {{ testrun.passed_style.icon|safe }}
                        <i title="Waived test (this result does not affect overall test result)"  class="fas {% include 'waived_icon.html' with waived=testrun.waived %}"></i>
                        {% if testrun.issue_records.exists %}
                        <i title="This test was recorded as an issue." class="fas fa-bug text-danger"></i>
                        {% endif %}
                      </td>
                      <td>{{ testrun.test.name }}</td>
                      <td>{{ testrun.kernel_arch.name }}</td>
                      <td>{% include "link_beaker_task.html" with test=testrun.beakertestrun %}</td>
                      <td>{% include "link_gitlab_job.html" with jid=testrun.beakertestrun.jid %}</td>
                  </tr>
                  {% endif %}
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          {% if perms.datawarehouse.delete_issuerecord %}
          <button type="button" class="btn btn-danger" href="#" data-toggle="modal" data-dismiss="modal" data-target="#deleteRecord{{ record.id }}">Delete</button>
          {% endif %}
          {% if perms.datawarehouse.change_issuerecord %}
          <button type="submit" class="btn btn-primary">Save</button>
          {% endif %}
        </div>
      </form>
    </div>
  </div>
</div>
<script src="/static/js/custom.js"></script>
<!-- End Edit Issue Record Modal -->

datawarehouse/templates/modal_new_issue_regex.html
<div class="modal fade" id="issueRegexModal" tabindex="-1" role="dialog" aria-labelledby="issueRegexModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
          <h5 class="modal-title" id="issueRegexModalLabel">Create Issue Regex</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="/issue/regex" method="POST">
          {% csrf_token %}
          <div class="row">
            <div class="col-xl-12">
              <div class="form-group">
                <label for="issueid">Issue</label>
                <div class="input-group">
                  <input type="text"
                         id="issue_type_filter"
                         placeholder="Text to filter issue types in the dropdown below" />
                  <select required="required" class="form-control" id="issue_id_select" name="issue_id_select">
                  <option disabled selected>Select an option</option>
                    {% for issue in issues %}
                    <option value="{{ issue.id }}">{{ issue.kind.tag  }} | {{ issue.description }}</option>
                    {% endfor %}
                  </select>
                </div>
                {% if perms.datawarehouse.add_issue %}
                <div align="right">
                  <a href="{% url 'issue_list' 'unresolved' %}?new=true&redirect_to={{ request.get_full_path }}%23issueregex">Create new issue</a>
                </div>
                {% endif %}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xl-12">
                <div class="form-group">
                  <label for="issue_regex_id">ID</label>
                  <input type="text" class="form-control" name="issue_regex_id" placeholder="Autogenerated" id="issue_regex_id" readonly>
                </div>
                <div class="form-group">
                  <label for="issue_regex_text_match">Text Match</label>
                  <input type="text" class="form-control" name="text_match" placeholder="Regex to look for in the logs" id="issue_regex_text_match" >
                </div>
                <div class="form-group">
                  <label class="optional" for="issue_regex_test_name_match">Test Name Match</label>
                  <input type="text" class="form-control" name="test_name_match" placeholder="Regex to match the test name" id="issue_regex_test_name_match" >
                </div>
                <div class="form-group">
                  <label class="optional" for="issue_regex_file_name_match">File Name Match</label>
                  <input type="text" class="form-control" name="file_name_match" placeholder="Regex to match the file name" id="issue_regex_file_name_match" >
                </div>
                <input type="hidden" id="action" name="action" value="new"/>
            </div>
          </div>
          </br>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            {% if perms.datawarehouse.delete_issueregex %}
            <div id="delete_issue_regex">
              <button type="submit" name="action" value="delete" class="btn btn-danger">Delete</button>
            </div>
            {% endif %}
            {% if perms.datawarehouse.change_issueregex or perms.datawarehouse.add_issueregex %}
            <button type="submit" class="btn btn-primary">Save</button>
            {% endif %}
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<script src="/static/js/custom.js"></script>
<script>
  const issueTypes = [
      {% for issue in issues %}
      {
          id: {{ issue.id }},
          tag: "{{ issue.kind.tag  }}",
          description: "{{ issue.description }}"
      },
      {% endfor %}
  ];

  document.getElementById('issue_type_filter').addEventListener('input', function(e) {
      filterDropdown(e.target.value, 'issue_id_select', issueTypes);
  });
</script>

datawarehouse/templates/pipeline_actions_dropdown.html
<span class="dropdown">
  <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Actions
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a href="/api/1/pipeline/{{pipeline.pipeline_id}}" class="dropdown-item">View in API</a>
    {% if perms.datawarehouse.add_issuerecord %}
    <a class="dropdown-item" data-toggle="modal" data-target="#issueRecordModal" href="#">Add Issue Record</a>
    {% endif %}
  </div>
</span>

datawarehouse/templates/waived_icon.html
{% if waived == True %}
fa-flag text-warning
{% else %}
{% endif %}