datawarehouse/api/kcidb/urls.py
"""Urls file."""
from django.urls import path

from . import views

urlpatterns = [
    path('data/<str:kind>', views.KCIDBView.as_view(),),
    path('submit', views.Submit.as_view()),

    path('revisions',
         views.RevisionList.as_view(), name='kcidb.revisions.list'),
    path('revisions/<str:id>',
         views.RevisionGet.as_view(), name='kcidb.revisions.get'),
    path('revisions/<str:id>/builds',
         views.BuildList.as_view(), name='kcidb.builds.list'),
    path('revisions/<str:id>/issues',
         views.RevisionIssueOccurrence.as_view(), name='kcidb.revisions.issues'),
    path('revisions/<str:id>/issues/<int:issue_id>',
         views.RevisionIssueOccurrence.as_view(), name='kcidb.revisions.issues'),
    path('builds/<str:id>',
         views.BuildGet.as_view(), name='kcidb.builds.get'),
    path('builds/<str:id>/tests',
         views.TestList.as_view(), name='kcidb.tests.list'),
    path('builds/<str:id>/issues',
         views.BuildIssueOccurrence.as_view(), name='kcidb.builds.issues'),
    path('builds/<str:id>/issues/<int:issue_id>',
         views.BuildIssueOccurrence.as_view(), name='kcidb.builds.issues'),
    path('tests/<str:id>',
         views.TestGet.as_view(), name='kcidb.tests.get'),
    path('tests/<str:id>/issues',
         views.TestIssueOccurrence.as_view(), name='kcidb.tests.issues'),
    path('tests/<str:id>/issues/<int:issue_id>',
         views.TestIssueOccurrence.as_view(), name='kcidb.tests.issues'),
]

datawarehouse/api/urls.py
"""Urls file."""
from django.urls import path, include
from . import views

urlpatterns = [
    path('1/pipeline/<int:pipeline_id>/action', views.PipelineAction.as_view()),
    path('1/pipeline/<int:pipeline_id>/issue/record', views.PipelineIssueRecord.as_view()),
    path('1/pipeline/<int:pipeline_id>/issue/record/<int:record_id>', views.PipelineIssueRecord.as_view()),
    path('1/pipeline/<int:pipeline_id>/report', views.PipelineReport.as_view()),
    path('1/pipeline/<int:pipeline_id>', views.Pipeline.as_view()),
    path('1/pipeline/<int:pipeline_id>/patches', views.PipelinePatches.as_view()),
    path('1/pipeline/<int:pipeline_id>/jobs/<str:stage_name>', views.PipelineJobs.as_view()),
    path('1/pipeline/<int:pipeline_id>/jobs/<str:stage_name>/failures', views.PipelineFailedJobs.as_view()),
    path('1/pipeline/failures/<str:stage_name>', views.PipelineByFailures.as_view()),
    path('1/issue/<int:issue_id>/record', views.IssueRecords.as_view()),
    path('1/issue/<int:issue_id>', views.Issue.as_view()),
    path('1/issue', views.Issue.as_view()),
    path('1/issue/regex', views.IssueRegex.as_view()),
    path('1/report/missing', views.ReportMissing.as_view()),
    path('1/test/<int:test_id>/issue/record', views.TestIssueRecord.as_view()),
    path('1/test/<int:test_id>/stats', views.TestStats.as_view()),
    path('1/test/<int:test_id>', views.TestSigle.as_view()),
    path('1/test', views.TestList.as_view()),
    path('1/kcidb/', include('datawarehouse.api.kcidb.urls')),
]

datawarehouse/urls.py
# -*- coding: utf-8 -*-
# Copyright (c) 2018 Red Hat, Inc. All rights reserved. This copyrighted
# material is made available to anyone wishing to use, modify, copy, or
# redistribute it subject to the terms and conditions of the GNU General Public
# License v.2 or later.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
"""Urls file."""
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

import debug_toolbar

from datawarehouse import views, views_kcidb
from datawarehouse.api.kcidb.views import KCIDBView

urlpatterns = [
    path('', RedirectView.as_view(url='dashboard', permanent=False)),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('confidence/<str:group>', views.confidence,),
    path('cron', views.cron_run,),
    path('dashboard', views.dashboard, name='Dashboard'),
    path('details/<str:group>/<int:item_id>', views.details,),
    path('issue/list/<str:group>', views.issue_list, name='issue_list'),
    path('issue/list', RedirectView.as_view(url='list/unresolved', permanent=False)),
    path('issue/regex', views.issue_regex, name='issue_regex'),
    path('issue', views.issue_new_or_edit,),
    path('issue/<int:issue_id>/resolve', views.issue_resolve,),
    path('issuerecord/<int:issue_record_id>/modify', views.issuerecord_modify),
    path('patches/submitter/<str:group>', views.patch_get_by_submitter),
    path('patches/summary/<str:group>', views.patch_summary),
    path('patches/submitter', RedirectView.as_view(url='submitter/tested', permanent=False, query_string=True)),
    path('patches', RedirectView.as_view(url='patches/summary/tested', permanent=False)),
    path('pipeline/summary', RedirectView.as_view(url='summary/all', permanent=False)),
    path('pipeline/summary/<str:tree>', views.pipeline_summary),
    path('pipeline/failures/<str:group>', views.pipelines_by_failure),
    path('pipeline/failures', RedirectView.as_view(url='failures/all', permanent=False)),
    path('pipeline/<int:pipeline_id>', views.pipeline_get, name='pipeline_get'),
    path('pipeline/<int:pipeline_id>/issue', views.pipeline_issue),
    path('pipeline/<int:pipeline_id>/issue/<int:issue_record_id>/delete', views.pipeline_issue_delete),
    path('pipeline/submitter', views.pipelines_get_by_submitter),
    path('pipeline/running', views.pipelines_running,),
    path('metrics', RedirectView.as_view(url='metrics/all', permanent=False)),
    path('metrics/<str:tree>', views.metrics,),

    path('kcidb/issues/occurrences', views_kcidb.kcidb_issue, name='views.kcidb.issues'),
    path('kcidb/revisions',
         views_kcidb.revisions_list, name='views.kcidb.revisions'),
    path('kcidb/revisions/<int:revision_iid>',
         views_kcidb.revisions_get, name='views.kcidb.revisions'),
    path('kcidb/builds/<int:build_iid>',
         views_kcidb.builds_get, name='views.kcidb.builds'),
    path('kcidb/tests/<int:test_iid>',
         views_kcidb.tests_get, name='views.kcidb.tests'),


    # The following url is only for compatibility.
    # It should be removed as soon as de kcidb scripts use the new endpoint.
    path('kcidb/1/data/<str:kind>', KCIDBView.as_view(),),
    path('api/', include('datawarehouse.api.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
] \
    + static(settings.MEDIA_PATH, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

datawarehouse/models/kcidb_models.py
"""KCIDB schema models file."""
from email.utils import parseaddr

from cki_lib.misc import get_nested_key
from django.db import models

from datawarehouse import models as dw_models
from datawarehouse import signals


class AlreadySubmitted(Exception):
    """Object is already present in the DB."""


class MissingParent(Exception):
    """Object's parent is missing."""


def is_cki_submission(data):
    """Return True if this data matches a cki pipeline."""
    misc = data.get('misc', {})
    return {'pipeline', 'job'}.issubset(set(misc.keys()))


class Maintainer(models.Model):
    """Model for Maintainer."""

    name = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        """Return __str__ formatted."""
        return f'{self.name} <{self.email}>'

    @classmethod
    def create_from_address(cls, address):
        """Create Maintainer from address."""
        name, email = parseaddr(address)
        maintainer = cls.objects.update_or_create(
            email=email,
            defaults={'name': name},
        )[0]
        return maintainer


class KCIDBOrigin(models.Model):
    """Model for KCIDBOrigin."""

    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        """Return __str__ formatted."""
        return self.name

    @classmethod
    def create_from_string(cls, name):
        """Create KCIDBOrigin from string."""
        return cls.objects.get_or_create(name=name)[0]


class KCIDBRevisionManager(models.Manager):
    # pylint: disable=too-few-public-methods
    """Manager for KCIDBRevision."""

    def aggregated(self):
        # pylint: disable=too-many-locals
        """Add aggregated information."""
        revision = KCIDBRevision.objects.filter(id=models.OuterRef('id'))
        revision_triaged = revision.exclude(issues=None)
        revision_untriaged = revision.filter(
            valid=False,
            issues=None
        )

        builds_run = KCIDBBuild.objects.filter(revision__id=models.OuterRef('id'))
        builds_pass = builds_run.filter(valid=True)
        builds_fail = builds_run.filter(valid=False)
        builds_triaged = builds_run.exclude(issues=None)
        builds_untriaged = (
            KCIDBBuild.objects
            .filter_untriaged()
            .filter(revision__id=models.OuterRef('id'))
        )

        tests_run = KCIDBTest.objects.filter(build__revision__id=models.OuterRef('id'))
        tests_pass = tests_run.filter(status__name='PASS')
        tests_skip = tests_run.filter(status__name='SKIP')
        tests_fail = tests_run.filter(status__name='FAIL', waived=False)
        tests_triaged = tests_run.exclude(issues=None)
        tests_untriaged = (
            KCIDBTest.objects
            .filter_untriaged()
            .filter(build__revision__id=models.OuterRef('id'))
        )

        counts = {
            'builds_run': builds_run,
            'builds_pass': builds_pass,
            'builds_fail': builds_fail,
            'tests_run': tests_run,
            'tests_pass': tests_pass,
            'tests_skip': tests_skip,
            'tests_fail': tests_fail,
        }

        annotations = {
            'stats_revision_triaged': models.Exists(revision_triaged),
            'stats_revision_untriaged': models.Exists(revision_untriaged),
            'stats_builds_passed': ~models.Exists(builds_fail),
            'stats_builds_triaged': models.Exists(builds_triaged),
            'stats_builds_untriaged': models.Exists(builds_untriaged),
            'stats_tests_passed': ~models.Exists(tests_fail),
            'stats_tests_triaged': models.Exists(tests_triaged),
            'stats_tests_untriaged': models.Exists(tests_untriaged),
        }

        # Add count element for all the queries listed on $counts.
        for name, query in counts.items():
            count = query.values('id').annotate(c=models.Count('*')).values('c')
            count.query.set_group_by()
            annotations[f'stats_{name}_count'] = models.Subquery(count, output_field=models.IntegerField())

        return self.annotate(**annotations)


class KCIDBRevision(models.Model):
    """Model for KCIDBRevision."""

    iid = models.AutoField(primary_key=True)

    id = models.CharField(max_length=300, unique=True)
    origin = models.ForeignKey(KCIDBOrigin, on_delete=models.PROTECT)
    tree = models.ForeignKey('GitTree', on_delete=models.PROTECT, null=True, blank=True)
    git_repository_url = models.URLField(null=True, blank=True)
    git_repository_branch = models.CharField(max_length=200, null=True, blank=True)
    git_commit_hash = models.CharField(max_length=40, null=True, blank=True)
    git_commit_name = models.CharField(max_length=40, null=True, blank=True)
    patches = models.ManyToManyField('Patch', related_name='revisions', blank=True)
    message_id = models.CharField(null=True, blank=True, max_length=200)
    description = models.TextField(null=True, blank=True)
    publishing_time = models.DateTimeField(null=True, blank=True)
    discovery_time = models.DateTimeField(null=True, blank=True)
    contacts = models.ManyToManyField('Maintainer', related_name='revisions', blank=True)
    log = models.ForeignKey('Artifact', on_delete=models.SET_NULL, null=True, blank=True)
    valid = models.BooleanField(null=True)

    issues = models.ManyToManyField('Issue')

    objects = KCIDBRevisionManager()

    def __str__(self):
        """Return __str__ formatted."""
        return self.id

    class Meta:
        """Metadata."""

        ordering = ('-iid',)

    @property
    def is_public(self):
        """
        Return True if this KCIDBRevision is public.

        If there's no MergeRun associated, or any of the MergeRuns
        associated with this KCIDBRevision has a kernel_type
        different to 'upstream', consider it private.
        """
        return (
            self.mergerun_set.exists() and
            not self.mergerun_set.exclude(
                pipeline__variables__key='kernel_type',
                pipeline__variables__value='upstream'
            ).exists()
        )

    @property
    def is_triaged(self):
        """Return True if this revision is triaged."""
        if hasattr(self, 'stats_revision_triaged'):
            return self.stats_revision_triaged  # pylint: disable=no-member

        return self.issues.exists()

    @property
    def is_missing_triage(self):
        """Return True if this revision is missing triage."""
        if hasattr(self, 'stats_revision_untriaged'):
            return self.stats_revision_untriaged  # pylint: disable=no-member

        return not self.valid and not self.issues.exists()

    @property
    def triaged_builds(self):
        """Return list of triaged builds."""
        # pylint: disable=no-member
        if hasattr(self, 'stats_builds_triaged') and not self.stats_builds_triaged:
            return KCIDBBuild.objects.none()

        return self.kcidbbuild_set.exclude(issues=None)

    @property
    def untriaged_builds(self):
        """Return list of untriaged builds."""
        # pylint: disable=no-member
        if hasattr(self, 'stats_builds_untriaged') and not self.stats_builds_untriaged:
            return KCIDBBuild.objects.none()

        return self.kcidbbuild_set.filter_untriaged()

    @property
    def triaged_tests(self):
        """Return list of triaged tests."""
        # pylint: disable=no-member
        if hasattr(self, 'stats_tests_triaged') and not self.stats_tests_triaged:
            return KCIDBTest.objects.none()

        return (
            KCIDBTest.objects
            .filter(build__revision=self)
            .exclude(issues=None)
        )

    @property
    def untriaged_tests(self):
        """Return list of untriaged tests."""
        # pylint: disable=no-member
        if hasattr(self, 'stats_tests_untriaged') and not self.stats_tests_untriaged:
            return KCIDBTest.objects.none()

        return (
            KCIDBTest.objects
            .filter_untriaged()
            .filter(build__revision=self)
        )

    @property
    def has_objects_missing_triage(self):
        """Return if there are failures missing triage."""
        return (
            self.untriaged_tests.exists() or
            self.untriaged_builds.exists() or
            self.is_missing_triage
        )

    @property
    def has_objects_with_issues(self):
        """Return if the revision or one of it's builds and tests has any issues."""
        return (
            self.triaged_tests.exists() or
            self.triaged_builds.exists() or
            self.is_triaged
        )

    @classmethod
    def create_from_json(cls, data):
        """Create KCIDBRevision from kcidb json."""
        if cls.objects.filter(id=data['id'], origin__name=data['origin']).exists():
            raise AlreadySubmitted(f'Entry with {data["origin"]} {data["id"]} already exists.')

        misc = data.get('misc', {})

        log_url = data.get('log_url')
        log = dw_models.Artifact.create_from_url(log_url) if log_url else None

        tree_name = data.get('tree_name')
        tree = dw_models.GitTree.create_from_string(tree_name) if tree_name else None

        origin = KCIDBOrigin.create_from_string(data['origin'])
        revision = cls.objects.create(
            id=data['id'],
            origin=origin,
            tree=tree,
            git_repository_url=data.get('git_repository_url'),
            git_repository_branch=data.get('git_repository_branch'),
            git_commit_hash=data.get('git_commit_hash'),
            git_commit_name=data.get('git_commit_name'),
            message_id=data.get('message_id'),
            description=data.get('description'),
            publishing_time=data.get('publishing_time'),
            discovery_time=data.get('discovery_time'),
            valid=data.get('valid'),
            log=log,
        )

        for contact in data.get('contacts', []):

datawarehouse/models/message_models.py
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2018-2019 Red Hat, Inc.

# pylint: disable=too-few-public-methods

"""Models related to messages."""

from django.db import models


class MessagePending(models.Model):
    """Model for MessagePending."""

    body = models.TextField()
    exchange = models.CharField(max_length=50)

    def __str__(self):
        """Return __str__ formatted."""
        return self.body

datawarehouse/templates/web/kcidb/revision.html
{% extends "base.html" %}
{% load styles %}
{% load getattribute %}

{% block title %}
Revision
{% endblock %}

{% block header %}
Revision
{% endblock %}

{% block content %}

{% with kind='revision' item=revision %}
{% include 'modal_new_issue_occurrence.html' %}
{% endwith %}

<!-- Start dropdown menu -->
<div class="col-xl-4 col-md-6 mb-4">
  <div class="row">
    <span class="dropdown">
      <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Actions
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a href="{% url 'kcidb.revisions.get' revision.iid %}" class="dropdown-item">View in API</a>
        {% if perms.datawarehouse.change_kcidbrevision or perms.datawarehouse.change_kcidbbuild or perms.datawarehouse.change_kcidbtest %}
        <a class="dropdown-item" data-toggle="modal" data-target="#issueOccurrenceModal" href="#">Associate Issue</a>
        {% endif %}
      </div>
    </span>
  </div>
</div>
<!-- End dropdown menu -->

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'views.kcidb.revisions' %}">All</a></li>
    <li class="breadcrumb-item active" aria-current="page">Revision</li>
  </ol>
</nav>

<div class="row">
  <div class="col-xl-4 col-md-4 mb-2">
    <div class="card border-left-{{ revision.valid|get_style|getattribute:'color' }} shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-uppercase mb-1">Revision Status</div>
            <div class="h5 mb-0 font-weight-bold text-{{ revision.valid|get_style|getattribute:'color' }}">{{ revision.valid|yesno:'Valid,Not Valid' }}</div>
          </div>
          <div class="col-auto">
            {{ revision.valid|get_style|getattribute:'icon_big'|safe }}
          </div>
        </div>
      </div>
    </div>
  </div>

  {% if revision.stats_builds_run_count %}
  <div class="col-xl-4 col-md-4 mb-2">
    <div class="card border-left-{{ revision.stats_builds_passed|get_style|getattribute:'color' }} shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-uppercase mb-1">Build Status</div>
            <div class="h5 mb-0 font-weight-bold text-{{ revision.stats_builds_passed|get_style|getattribute:'color' }}">{{ revision.stats_builds_passed|yesno:'Passed,Failed' }}</div>
          </div>
          <div class="col-auto">
            {{ revision.stats_builds_passed|get_style|getattribute:'icon_big'|safe }}
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endif %}

  {% if revision.stats_tests_run_count %}
  <div class="col-xl-4 col-md-4 mb-2">
    <div class="card border-left-{{ revision.stats_tests_passed|get_style|getattribute:'color' }} shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-uppercase mb-1">Test Status</div>
            <div class="h5 mb-0 font-weight-bold text-{{ revision.stats_tests_passed|get_style|getattribute:'color' }}">{{ revision.stats_tests_passed|yesno:'Passed,Failed' }}</div>
          </div>
          <div class="col-auto">
            {{ revision.stats_tests_passed|get_style|getattribute:'icon_big'|safe }}
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
</div>

<div class="row">
  <div class="col-xl-12 mb-2">
    <div class="card">
      <div class="card-header border-left-{{ revision.valid|get_style|getattribute:'color' }}">
        <label>Revision ID: </label>
        {{ revision.id }}
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-6">
            <label>Origin:</label> {{ revision.origin|default:'' }}
            </br>
          </div>

          <div class="col-6">
            <label>Tree:</label> {{ revision.tree|default:'' }}
            </br>
          </div>

          <div class="col-6">
            <label>Repository URL:</label> {{ revision.git_repository_url|default:'' }}
            </br>
          </div>

          <div class="col-6">
            <label>Repository Branch:</label> {{ revision.git_repository_branch|default:'' }}
            </br>
          </div>

          <div class="col-6">
            <label>Commit Hash:</label> {{ revision.git_commit_hash|default:'' }}
            </br>
          </div>

          <div class="col-6">
            <label>Commit Name:</label> {{ revision.git_commit_name|default:'' }}
            </br>
          </div>

          <div class="col-6">
            <label>Message ID:</label> {{ revision.message_id|default:'' }}
            </br>
          </div>

          <div class="col-6">
            <label>Description:</label> {{ revision.description|default:'' }}
            </br>
          </div>

          <div class="col-6">
            <label>Publishing Time:</label> {{ revision.publishing_time|default:'' }}
            </br>
          </div>

          <div class="col-6">
            <label>Discovery Time:</label> {{ revision.discovery_time|default:'' }}
            </br>
          </div>

          <div class="col-12">
            <label>Log URL:</label>
            <a href="{{ revision.log.url|default:'' }}">{{ revision.log.url|default:'' }}</a>
            </br>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% if revision.has_objects_missing_triage %}
{% with object=revision %}
{% include 'card_kcidb_untriaged.html' %}
{% endwith %}
{% endif %}

<!-- Display all revision issues. -->
{% for occurrence in issue_occurrences %}
  {% include 'card_issue_occurrence.html' %}
{% endfor %}

{% if revision.patches.exists %}
<div class="row">
  <div class="col-xl-12 mb-2">
    <div class="card shadow">
      <div class="card-header py-3">
        List of Patches
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-hover table-sm" width="100%" cellspacing="0">
            <tbody>
              {% for patch in revision.patches.all %}
                  <tr class="d-flex">
                    {% include 'tables/cell_clickable.html' with size='6' text=patch.subject url=patch.url %}
                    {% include 'tables/cell_clickable.html' with size='6' text=patch.url url=patch.url %}
                  </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}

{% if builds.exists %}
<div class="row">
  <div class="col-xl-12 mb-2">
    <div class="card shadow">
      <div class="card-header py-3">
        List of Builds
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-hover table-sm" width="100%" cellspacing="0">
            <tbody>
              {% for build in builds %}
                {% with url_name='views.kcidb.builds' id=build.iid %}
                  <tr class="d-flex border-left-{{ build.all_passed|get_style|getattribute:'color' }}  {{ build.all_passed|get_style|getattribute:'row' }}">
                    {% include 'tables/cell_clickable.html' with size='2' text=build.id extra_attr='align="center"' %}
                    {% include 'tables/cell_clickable.html' with size='8' text=build.architecture.name %}
                    {% include 'tables/cell_clickable.html' with size='1' text='Build: ' emoji=build.valid|get_style|getattribute:'icon'|safe %}

                    {% if build.kcidbtest_set.exists %}
                      {% include 'tables/cell_clickable.html' with size='1' text='Tests: ' emoji=build.tests_passed|get_style|getattribute:'icon'|safe %}
                    {% else %}
                      {% include 'tables/cell_clickable.html' with size='1' %}
                    {% endif %}
                  </tr>
                {% endwith %}
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}

{% endblock %}

{% block script %}
<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>

<script>
  var url = window.location.href;
  if (url.indexOf('#issueoccurrence') != -1) {
      $('#issueOccurrenceModal').modal('show');
  }
</script>
{% endblock %}

datawarehouse/templates/web/kcidb/revisions.html
{% extends "base.html" %}

{% block title %}
KCIDB Data
{% endblock %}

{% block header %}
KCIDB Data
{% endblock %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active">All</li>
  </ol>
</nav>

<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Latest Revisions</h6>
  </div>
  <div class="card-body">
    {% include 'tables/table_kcidb_revisions.html' %}
  </div>
</div>

{% with paginator=revisions %}
{% include 'paginator.html' %}
{% endwith %}

{% endblock %}

{% block script %}
<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>
{% endblock %}